spring:
  application:
    name: spring-cloud-first-client-admin-ribbon
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8764
eureka:
  client:
      service-url:
        defaultzone: http://localhost:8761/eureka/
      enabled: false
#    fetch-registry: false
#    register-with-eureka: true
