spring:
  application:
    name: spring-cloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8765
eureka:
  client:
      service-url:
        defaultzone: http://localhost:8761/eureka/
#        打开熔断器
feign:
  hystrix:
    enabled: true
#      enabled: false
#    fetch-registry: false
#    register-with-eureka: true